import { DestinyActivityModeType, DestinyClass } from "bungie-net-core/enums";

export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const newRaidHashes = [2192826039, 1541433876, 4129614942];
export const newDungeonHashes = [300092127, 1915770060, 3492566689, 4293676253];

export const destinyClassName: { [key: number]: string } = {
  [DestinyClass.Titan]: "Titan",
  [DestinyClass.Hunter]: "Hunter",
  [DestinyClass.Warlock]: "Warlock",
  [DestinyClass.Unknown]: "Unknown",
};

export const activityModeNames: { [key: number]: string } = {
  [DestinyActivityModeType.None]: "None",
  [DestinyActivityModeType.Story]: "Stories",
  [DestinyActivityModeType.Strike]: "Strikes",
  [DestinyActivityModeType.Raid]: "Raids",
  [DestinyActivityModeType.AllPvP]: "All PvP",
  [DestinyActivityModeType.Patrol]: "Patrol",
  [DestinyActivityModeType.AllPvE]: "All PvE",
  [DestinyActivityModeType.Control]: "Control",
  [DestinyActivityModeType.Clash]: "Clash",
  [DestinyActivityModeType.CrimsonDoubles]: "Crimson Doubles",
  [DestinyActivityModeType.Nightfall]: "Nightfall",
  [DestinyActivityModeType.HeroicNightfall]: "Heroic Nightfall",
  [DestinyActivityModeType.AllStrikes]: "All Strikes",
  [DestinyActivityModeType.IronBanner]: "Iron Banner",
  [DestinyActivityModeType.AllMayhem]: "All Mayhem",
  [DestinyActivityModeType.Supremacy]: "Supremacy",
  [DestinyActivityModeType.PrivateMatchesAll]: "Private Matches All",
  [DestinyActivityModeType.Survival]: "Survival",
  [DestinyActivityModeType.Countdown]: "Countdown",
  [DestinyActivityModeType.TrialsOfTheNine]: "Trials of the Nine",
  [DestinyActivityModeType.Social]: "Social",
  [DestinyActivityModeType.TrialsCountdown]: "Trials Countdown",
  [DestinyActivityModeType.TrialsSurvival]: "Trials Survival",
  [DestinyActivityModeType.IronBannerControl]: "Iron Banner Control",
  [DestinyActivityModeType.IronBannerClash]: "Iron Banner Clash",
  [DestinyActivityModeType.IronBannerSupremacy]: "Iron Banner Supremacy",
  [DestinyActivityModeType.ScoredNightfall]: "Scored Nightfall",
  [DestinyActivityModeType.ScoredHeroicNightfall]: "Scored Heroic Nightfall",
  [DestinyActivityModeType.Rumble]: "Rumble",
  [DestinyActivityModeType.AllDoubles]: "All Doubles",
  [DestinyActivityModeType.Doubles]: "Doubles",
  [DestinyActivityModeType.PrivateMatchesClash]: "Private Matches Clash",
  [DestinyActivityModeType.PrivateMatchesControl]: "Private Matches Control",
  [DestinyActivityModeType.PrivateMatchesSupremacy]:
    "Private Matches Supremacy",
  [DestinyActivityModeType.PrivateMatchesCountdown]:
    "Private Matches Countdown",
  [DestinyActivityModeType.PrivateMatchesSurvival]: "Private Matches Survival",
  [DestinyActivityModeType.PrivateMatchesMayhem]: "Private Matches Mayhem",
  [DestinyActivityModeType.PrivateMatchesRumble]: "Private Matches Rumble",
  [DestinyActivityModeType.HeroicAdventure]: "Heroic Adventure",
  [DestinyActivityModeType.Showdown]: "Showdown",
  [DestinyActivityModeType.Lockdown]: "Lockdown",
  [DestinyActivityModeType.Scorched]: "Scorched",
  [DestinyActivityModeType.ScorchedTeam]: "Scorched Team",
  [DestinyActivityModeType.Gambit]: "Gambit",
  [DestinyActivityModeType.AllPvECompetitive]: "All PvE Competitive",
  [DestinyActivityModeType.Breakthrough]: "Breakthrough",
  [DestinyActivityModeType.BlackArmoryRun]: "Black Armory Run",
  [DestinyActivityModeType.Salvage]: "Salvage",
  [DestinyActivityModeType.IronBannerSalvage]: "Iron Banner Salvage",
  [DestinyActivityModeType.PvPCompetitive]: "PvP Competitive",
  [DestinyActivityModeType.PvPQuickplay]: "PvP Quickplay",
  [DestinyActivityModeType.ClashQuickplay]: "Clash Quickplay",
  [DestinyActivityModeType.ClashCompetitive]: "Clash Competitive",
  [DestinyActivityModeType.ControlQuickplay]: "Control Quickplay",
  [DestinyActivityModeType.ControlCompetitive]: "Control Competitive",
  [DestinyActivityModeType.GambitPrime]: "Gambit Prime",
  [DestinyActivityModeType.Reckoning]: "Reckoning",
  [DestinyActivityModeType.Menagerie]: "Menagerie",
  [DestinyActivityModeType.VexOffensive]: "Vex Offensive",
  [DestinyActivityModeType.NightmareHunt]: "Nightmare Hunt",
  [DestinyActivityModeType.Elimination]: "Elimination",
  [DestinyActivityModeType.Momentum]: "Momentum",
  [DestinyActivityModeType.Dungeon]: "Dungeons",
  [DestinyActivityModeType.Sundial]: "Sundials",
  [DestinyActivityModeType.TrialsOfOsiris]: "Trials of Osiris",
  [DestinyActivityModeType.Dares]: "Dares",
  [DestinyActivityModeType.Offensive]: "Offensives",
  [DestinyActivityModeType.LostSector]: "Lost Sectors",
  [DestinyActivityModeType.Rift]: "Rift",
  [DestinyActivityModeType.ZoneControl]: "Zone Control",
  [DestinyActivityModeType.IronBannerRift]: "Iron Banner Rift",
  [DestinyActivityModeType.IronBannerZoneControl]: "Iron Banner Zone Control",
  [DestinyActivityModeType.Relic]: "Relic",
};
